[package]
authors = ["sark"]
description = "A simple terminal for rendering ascii in bevy."
edition = "2024"
homepage = "https://github.com/sarkahn/bevy_ascii_terminal"
keywords = ["bevy", "ascii", "terminal", "roguelike", "tilemap"]
license = "MIT"
name = "bevy_ascii_terminal"
readme = "README.md"
repository = "https://github.com/sarkahn/bevy_ascii_terminal"
version = "0.17.0-dev"

[dependencies]
enum-ordinalize = "4.3.0"
thiserror = "1.0.56"
flate2 = "1.0"
byteorder = "1"
sark_grids = "0.6.2"

[dev-dependencies]
fastnoise-lite = "1.1.1"
rand = "0.8.4"

[dependencies.bevy]
git = "https://github.com/bevyengine/bevy"
rev = "2a2e0a855562612cb59176959b5807f0530eecc8"
default-features = false
features = ["std", "png", "bevy_render", "bevy_asset", "bevy_sprite", "bevy_window", "bevy_color"]

[dev-dependencies.bevy]
git = "https://github.com/bevyengine/bevy"
rev = "2a2e0a855562612cb59176959b5807f0530eecc8"
default-features = false
features = ["bevy_winit"]

[target.'cfg(unix)'.dependencies.bevy]
git = "https://github.com/bevyengine/bevy"
rev = "2a2e0a855562612cb59176959b5807f0530eecc8"
default-features = false
features = ["x11"]

[target.'cfg(target_arch = "wasm32")'.dependencies.bevy]
git = "https://github.com/bevyengine/bevy"
rev = "2a2e0a855562612cb59176959b5807f0530eecc8"
default-features = false
features = ["webgl2"]

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3